---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    dnf:
      update_cache: yes

  - name: Install httpd/apache package
    dnf:
      name: httpd
      state: latest

  - name: add php support for apache
    dnf:
      name: php
      state: latest
